all:
  children:
    network_devices:
      hosts:
        router1:
          ansible_host: 192.168.56.102
          ansible_network_os: ios
          ansible_user: cisco
          ansible_password: cisco123!
